### ISSUE TITLE
`confirm` function

### ISSUE THREAD

**Issue by jmervine** [odb/shml#31]
Add `confirm` with usage like so:

``` bash
# with success callback
on_succes() {
    echo "Success"
}
confirm "Did you succeed?" "on_success"

# with success and failure callbacks
on_failure() {
    echo "Failed"
}
confirm "Did you succeed?" "on_success" "on_failure"

# w/o callbacks
config "Did you succeed?" && echo "Why yes, yes I did!"
```

@jdorfman thoughts?

**Comment by jmervine** [comment]
In the same vein, I could add a `dialog` as well, which displays a message and takes a response string an returns it. The idea being to emulate javascript's `confirm` and `dialog` here, all nicely encapsulated.

**Comment by jmervine** [comment]
`confirm` should accept the following as an affirmative: `y`, `Y`, `yes`, `Yes`, `ok`, `OK`, `okay`, `Okay`, `OKAY`, `continue`, `Continue`, `CONTINUE`, `proceed`, `Proceed`, `PROCEED`... 

Everything else would be negative/no.

@jdorfman  can you think of anything else?

**Comment by jdorfman** [comment]
perfect

**Comment by jdorfman** [comment]
I think it is never too late to revive a 2-year-old feature request. This should be `v1.1.0`

![image](https://user-images.githubusercontent.com/398230/34425425-9d7fd3ae-ebe0-11e7-89df-ab07ea7b953c.png)
