### ISSUE TITLE
Error when sourcing

### ISSUE THREAD

**Issue by slmjkdbtl** [odb/shml#34]
Error Message

``` bash
/usr/local/bin/shml:360: = not found
```

Line 358 - 365

``` bash
# Usage / Examples
##
if [ "$0" == "$BASH_SOURCE" ]; then

if [[ $@ =~ .*-v.* ]]; then
  echo "shml version ${SHML_VERSION}"
  exit 0
fi
```

**Comment by jdorfman** [comment]
@voyga weird. How did you install shml?

**Comment by jmervine** [comment]
@Voyga (cc @jdorfman) Though testing, I'm seeing that the `==` method of testing strings doesn't work in `zsh`. Can you provide some information by running the following commands and pasting your output to assist me in confirming...

First, shell information:
```bash
$SHELL --version
```

Second, test the line in question alone:
```bash
if [ "foo" == "foo" ]; then echo "pass"; else echo "fail"; fi
```

Lastly, help me test a fix by running:
```bash
if [ "foo" = "foo" ]; then echo "pass"; else echo "fail"; fi
```

All that said, I'm not sure we want to (fully) support `zsh`, but I'm willing to make a few quick fixes and see if we can get it working.

**Comment by jmervine** [comment]
Upon further inspection (it only took a minute), we're not going to support shells outside of `bash` at this time. 

Ensure that you're running your script though bash by including `#!/usr/bin/env bash` or `#!/bin/bash` as the first line of the file,  or by running it like so `bash ./your_script.sh`.

I'll leave this open for now, awaiting the requested information to ensure that my assumption is correct. Cheers!

**Comment by jdorfman** [comment]
Thanks @jmervine

**Comment by Voyga** [comment]
Solved, Thanks. @jmervine

**Comment by jmervine** [comment]
@Voyga Mind clarifying what the issue was you were having in case someone else runs in to the same issue and comes across this thread in a search?

Thanks!
J

PS - Closing

**Comment by simoniz0r** [comment]
I know this is super old, but when trying to source this in `zsh` I just had to remove the second `=` in line 360, and it works fine.

```
if [ "$0" = "$BASH_SOURCE" ]; then
```

**Comment by jdorfman** [comment]
@simoniz0r thanks for the report. @jmervine I think it is time for a release. Maybe fix this and release #32 

LMK and I will start the docs.

**Comment by jmervine** [comment]
Revisiting based on @simoniz0r 's comment.

**Comment by jmervine** [comment]
Addressed on the following commit -- https://github.com/odb/shml/pull/32/commits/cd551bf9762c94032c17aecb0b090fc1fa27ec08
