### ISSUE TITLE
Remove Runnable Demo links

### ISSUE THREAD

**Issue by jdorfman** [odb/shml#37]
Runnable got acquired and shut down the service.

![image](https://user-images.githubusercontent.com/398230/34321058-04da0634-e7bb-11e7-8405-2307425fe420.png)

Need to remove the "Demo on Runnable" images in docs and README

![cloudapp annotation 2017-12-23 at 8 27 38 am png](https://user-images.githubusercontent.com/398230/34321075-4a8078e4-e7bb-11e7-9116-2dc9f8464994.png)

**Comment by jmervine** [comment]
@jdorfman 

Removed from readme here: https://github.com/odb/shml/commit/568b0495b49dd7ee8e07a75ae218ca7e5347f6a6

Created https://github.com/odb/shml/pull/38 to remove from site.

**Comment by jdorfman** [comment]
Removed the others. Missed one, @Mandihamza is on it. Keep open until then.

**Comment by jdorfman** [comment]
#41 closes this issue
