### ISSUE TITLE
[Security] nokogiri dependency

### ISSUE THREAD

**Issue by jdorfman** [odb/shml#40]
@jmervine is this something we need to worry about?

![image](https://user-images.githubusercontent.com/398230/34425117-115da786-ebde-11e7-8a0d-c5dc48a80f09.png)

https://github.com/odb/shml/network/dependencies#30372747

**Comment by jmervine** [comment]
This isn't something we really have to worry about, because the ruby code is only being used to build the static site, not in production. However, it doesn't hurt to fix it either. I'll push a fix to the branch you started.
